name: Angela Lamont // Presenter
favicon: null
layout_spectrum: 0.61697
typography_spectrum: 0.40368
title: Angela Lamont // Presenter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f3eadb'
    - '#594d3a'
    - '#b6a58b'
    - '#d10015'
  brandStrength: 0.6875
  lightness: 0.0625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
