name: Angela Lamont // Presenter
favicon: null
layout_spectrum: 0.18246055906638503
typography_spectrum: 0.31628
title: Angela Lamont // Presenter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#230004'
    - '#5f422f'
    - '#86958d'
    - '#ff2b1c'
    - '#a01610'
  brandStrength: 0.4375
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
