name: Angela Lamont // Presenter
favicon: null
layout_spectrum: 1
typography_spectrum: 0.64533
title: Angela Lamont // Presenter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#230004'
    - '#5f422f'
    - '#86958d'
    - '#ff2b1c'
    - '#a01610'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
