name: Angela Lamont Presenter
favicon: null
layout_spectrum: 0.18246055906638503
typography_spectrum: 0.6593628793489188
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.3613540136720985
  lightness: 0.20260754227638245
  saturation: 0.08922762284055352
  rhythmicContrast: 0.6588124248664826
purpose: []
